const pool = require('../config/db');

const devicesToImport = [
  // 1. ASCG HQ (5 items)
  {
    ip_address: '192.168.99.1',
    device_name: 'DC Server / DNS',
    brand_name: 'DELL',
    model: 'PowerEdgeR310',
    login_user: 'Root',
    login_password: '@QAZxsw3',
    manage_program: 'https://192.168.99.1:8333',
    login_ssid: 'ASCGGROUP\\Administrator',
    access_key: 'isit@dm%n',
    purchase_date: null,
    category: 'Server',
    branch_name: 'ASCG HQ',
    remark: 'Virtual Server on R310',
    status: 'active'
  },
  {
    ip_address: '192.168.99.2',
    device_name: 'DNS2/Sharefiles',
    brand_name: 'DELL',
    model: 'PowerEdgeT140',
    login_user: 'ascg_admin',
    login_password: '@QAZxsw3',
    manage_program: 'Win2012R2 /Sharefile/ExpressA',
    login_ssid: 'Administrator',
    access_key: '@dminFS',
    purchase_date: null,
    category: 'Server',
    branch_name: 'ASCG HQ',
    remark: 'ASCGGROUP\\Administrator',
    status: 'active'
  },
  {
    ip_address: '192.168.99.22',
    device_name: 'CCTV HQ Recorder',
    brand_name: 'HiKvision',
    model: 'DS-7332HQHI-K4',
    login_user: 'admin',
    login_password: 'admin1234',
    manage_program: '9-Dot Pattern (S / เลข 5)',
    login_ssid: 'S/N: DS-7332HQHI-K43220210817CCWRG55450628WCVU',
    access_key: null,
    purchase_date: '2021-11-10',
    category: 'CCTV',
    branch_name: 'ASCG HQ',
    remark: '32-Channel NVR System',
    status: 'active'
  },
  {
    ip_address: '192.168.99.241',
    device_name: 'Access Point A-F1',
    brand_name: 'TP-Link',
    model: 'EAP610',
    login_user: 'admin',
    login_password: 'isit@dm%n',
    manage_program: 'Unifi Manage',
    login_ssid: 'AIA-WiFi ,Guest ,Multi-SSID',
    access_key: 'ASCGInterpro',
    purchase_date: '2023-06-08',
    category: 'Access Point',
    branch_name: 'ASCG HQ',
    remark: 'POD2300433 (AIA ชั้น 1)',
    status: 'active'
  },
  {
    ip_address: '192.168.99.254',
    device_name: 'Core Firewall FGT-60E',
    brand_name: 'Fortigate',
    model: 'FGT-60E',
    login_user: 'admin / ascg_admin',
    login_password: 'isit@dm%n',
    manage_program: 'https://forticloud.com',
    login_ssid: 'itd@ascggroup.com',
    access_key: 'P@ssw0rdITD',
    purchase_date: '2022-01-15',
    category: 'Network & Security',
    branch_name: 'ASCG HQ',
    remark: 'Forticloud Primary Gateway',
    status: 'active'
  },

  // 2. BD7 (8 items)
  {
    ip_address: '192.168.99.4',
    device_name: 'iDRAC Remote Management',
    brand_name: 'DELL',
    model: 'PowerEdgeT140',
    login_user: 'root',
    login_password: 'isit@dm%n',
    manage_program: 'https://192.168.99.4',
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Server',
    branch_name: 'BD7',
    remark: 'Default Password หลังเครื่อง',
    status: 'active'
  },
  {
    ip_address: '192.168.99.23',
    device_name: 'Backup Router',
    brand_name: 'TRENDnet',
    model: 'TEW-432BRP',
    login_user: 'admin',
    login_password: 'isit@dm%n',
    manage_program: 'http://192.168.1.1',
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Network & Security',
    branch_name: 'BD7',
    remark: 'Default admin/admin',
    status: 'active'
  },
  {
    ip_address: '192.168.7.17',
    device_name: 'Time / Finger Access F1 BD7',
    brand_name: 'ZKTeco',
    model: 'F18',
    login_user: 'admin',
    login_password: 'adminpassword',
    manage_program: 'ZKTime 5.0 Program Manage',
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD7',
    remark: 'Time Access Scan BD7',
    status: 'active'
  },
  {
    ip_address: '192.168.1.1',
    device_name: '3BB Fiber Modem BD7',
    brand_name: '3BB / Huawei',
    model: 'HG8145X6',
    login_user: 'admin',
    login_password: '3bbpass123',
    manage_program: '192.168.1.1',
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Network & Security',
    branch_name: 'BD7',
    remark: 'Internet 3BB Fiber FTTX BD7',
    status: 'active'
  },
  {
    ip_address: '192.168.1.7',
    device_name: 'NEC VoIP BD7 (Port 5060)',
    brand_name: 'NEC',
    model: 'SL1000',
    login_user: 'tech',
    login_password: 'necpass123',
    manage_program: 'WebPro SL1000',
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD7',
    remark: 'SIP Port 5060',
    status: 'active'
  },
  {
    ip_address: '192.168.1.8',
    device_name: 'NEC VoIP BD7 (Port 10020)',
    brand_name: 'NEC',
    model: 'SL1000',
    login_user: 'tech',
    login_password: 'necpass123',
    manage_program: 'WebPro SL1000',
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD7',
    remark: 'RTP Port 10020',
    status: 'active'
  },
  {
    ip_address: '192.168.1.16',
    device_name: 'CCTV DVR BD7',
    brand_name: 'T-Gard',
    model: 'PS-7908MI',
    login_user: 'admin',
    login_password: '12345',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'CCTV',
    branch_name: 'BD7',
    remark: 'CCTV Recorder BD7',
    status: 'active'
  },
  {
    ip_address: '192.168.7.16',
    device_name: 'CCTV NVR ตึก 7',
    brand_name: 'HiKvision',
    model: 'DS-7608NI-K1',
    login_user: 'admin',
    login_password: '19911991',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'CCTV',
    branch_name: 'BD7',
    remark: 'Port 8000, HTTP 8080',
    status: 'active'
  },

  // 3. BD8 (23 items)
  {
    ip_address: '192.168.99.5',
    device_name: 'NAS Storage BD8',
    brand_name: 'QNAP',
    model: 'TS-435A',
    login_user: 'ascg_admin',
    login_password: '1sitAdmin',
    manage_program: 'https://helpdesk.qnap.com',
    login_ssid: 'User Thanakrit.k@ascggroup.com',
    access_key: null,
    purchase_date: null,
    category: 'Server',
    branch_name: 'BD8',
    remark: 'MyQNAPCloud Access',
    status: 'active'
  },
  {
    ip_address: '192.168.8.1',
    device_name: 'Rack 27U BD8',
    brand_name: 'Germany Export',
    model: '27U',
    login_user: null,
    login_password: null,
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: '2014-07-01',
    category: 'Other',
    branch_name: 'BD8',
    remark: 'Rack 27U 19" Germany Export Location 8-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.8.2',
    device_name: 'ASCG-SERV01 (DC, CRM, ExpressI, ShareFile)',
    brand_name: 'HP',
    model: 'DL320e Gen8',
    login_user: 'Administrator',
    login_password: 'P@ssw0rdServ01',
    manage_program: null,
    login_ssid: null,
    access_key: '2008 R2 Std.',
    purchase_date: '2014-07-01',
    category: 'Server',
    branch_name: 'BD8',
    remark: 'Xeon 4GB 1TB Blade Server',
    status: 'active'
  },
  {
    ip_address: '192.168.8.3',
    device_name: 'ASC-SERVER01 (ExpressA)',
    brand_name: 'HP',
    model: 'ML310e Gen8',
    login_user: 'Administrator',
    login_password: 'P@ssw0rdServ01',
    manage_program: null,
    login_ssid: null,
    access_key: '2003 R2 Ent.',
    purchase_date: null,
    category: 'Server',
    branch_name: 'BD8',
    remark: 'PC Server ExpressA Location 8-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.8.4',
    device_name: 'NAV-SERVER (Dynamic NAV)',
    brand_name: 'Lenovo',
    model: 'x3650',
    login_user: 'Administrator',
    login_password: 'P@ssw0rdNavServer',
    manage_program: null,
    login_ssid: null,
    access_key: '2012 R2 Std. / 2016 20 User',
    purchase_date: null,
    category: 'Server',
    branch_name: 'BD8',
    remark: 'Blade Server RDP 5 User',
    status: 'active'
  },
  {
    ip_address: '192.168.8.5',
    device_name: 'Modem Router Internet 3BB Fiber BD8',
    brand_name: 'Huawei',
    model: 'HG8245H',
    login_user: 'admin',
    login_password: '3bbpass123',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Network & Security',
    branch_name: 'BD8',
    remark: '3BB Fiber Internet Modem Router',
    status: 'active'
  },
  {
    ip_address: '192.168.8.6',
    device_name: 'Firewall Fortigate FGT90D BD8',
    brand_name: 'Fortigate',
    model: 'FGT90D',
    login_user: 'admin',
    login_password: 'isit@dm%n',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: '2014-07-01',
    category: 'Network & Security',
    branch_name: 'BD8',
    remark: 'Core Firewall BD8',
    status: 'active'
  },
  {
    ip_address: '192.168.8.7',
    device_name: 'LOG Analyzer IDR1000 BD8',
    brand_name: 'Nullsoft',
    model: 'IDR1000',
    login_user: 'admin',
    login_password: 'logpass123',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: '2014-07-01',
    category: 'Network & Security',
    branch_name: 'BD8',
    remark: 'ส่ง Log ไปเก็บที่อุปกรณ์ FLZ-200 ซอย 10',
    status: 'active'
  },
  {
    ip_address: '192.168.8.8',
    device_name: 'Switch Hub HP 1810-24 #1 BD8',
    brand_name: 'HP',
    model: '1810-24',
    login_user: 'admin',
    login_password: 'hppassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: '2014-07-01',
    category: 'Network & Security',
    branch_name: 'BD8',
    remark: 'Internal Managed Switch 24 Port',
    status: 'active'
  },
  {
    ip_address: '192.168.8.9',
    device_name: 'Switch Hub HP 1810-24 #2 BD8',
    brand_name: 'HP',
    model: '1810-24',
    login_user: 'admin',
    login_password: 'hppassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: '2014-07-01',
    category: 'Network & Security',
    branch_name: 'BD8',
    remark: 'Internal Managed Switch 24 Port',
    status: 'active'
  },
  {
    ip_address: '192.168.8.10',
    device_name: 'UPS LEONIC USV-1500 #1 BD8',
    brand_name: 'LEONIC',
    model: 'USV-1500',
    login_user: null,
    login_password: null,
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: '2014-07-01',
    category: 'Other',
    branch_name: 'BD8',
    remark: '1500VA UPS Power Supply',
    status: 'active'
  },
  {
    ip_address: '192.168.8.11',
    device_name: 'UPS LEONIC USV-1500 #2 BD8',
    brand_name: 'LEONIC',
    model: 'USV-1500',
    login_user: null,
    login_password: null,
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Other',
    branch_name: 'BD8',
    remark: '1500VA UPS Power Supply',
    status: 'active'
  },
  {
    ip_address: '192.168.8.12',
    device_name: 'Access Point UBiQUiTi UniFi F1 BD8',
    brand_name: 'UBiQUiTi',
    model: 'UniFi AP',
    login_user: 'admin',
    login_password: 'unifipassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Access Point',
    branch_name: 'BD8',
    remark: 'Access Point F1 8-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.8.13',
    device_name: 'Access Point UBiQUiTi UniFi F2 BD8',
    brand_name: 'UBiQUiTi',
    model: 'UniFi AP',
    login_user: 'admin',
    login_password: 'unifipassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Access Point',
    branch_name: 'BD8',
    remark: 'Access Point F2 8-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.8.14',
    device_name: 'Access Point UBiQUiTi UniFi F3 BD8',
    brand_name: 'UBiQUiTi',
    model: 'UniFi AP',
    login_user: 'admin',
    login_password: 'unifipassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Access Point',
    branch_name: 'BD8',
    remark: 'Access Point F3 8-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.8.15',
    device_name: 'Time / Door Access ZKT F18 F1 BD8',
    brand_name: 'ZKT',
    model: 'F18',
    login_user: 'admin',
    login_password: 'adminpassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD8',
    remark: 'Time / Door Access F1 8-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.8.16',
    device_name: 'Door Access ZKT F18 F2 BD8',
    brand_name: 'ZKT',
    model: 'F18',
    login_user: 'admin',
    login_password: 'adminpassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD8',
    remark: 'Door Access F2 8-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.8.17',
    device_name: 'Door Access ZKT F18 F3 BD8',
    brand_name: 'ZKT',
    model: 'F18',
    login_user: 'admin',
    login_password: 'adminpassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD8',
    remark: 'Door Access F3 8-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.8.18',
    device_name: 'PABX NEC SL1000 BD8',
    brand_name: 'NEC',
    model: 'SL1000',
    login_user: 'tech',
    login_password: 'necpass123',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD8',
    remark: 'PABX Telephone 8co/32ext 8-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.8.19',
    device_name: 'Printer Samsung C9201 BD8',
    brand_name: 'Samsung',
    model: 'C9201',
    login_user: 'admin',
    login_password: 'samsungpass',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Printer',
    branch_name: 'BD8',
    remark: 'Printer ISD 8-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.8.20',
    device_name: 'DVR CCTV T-Grad PS-7908MI BD8',
    brand_name: 'T-Grad',
    model: 'PS-7908MI',
    login_user: 'admin',
    login_password: '12345',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'CCTV',
    branch_name: 'BD8',
    remark: 'DVR CCTV Recorder 8-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.8.21',
    device_name: 'Printer HP MFP MP125a Site BangJak BD8',
    brand_name: 'HP',
    model: 'MFP MP125a',
    login_user: 'admin',
    login_password: 'hppassword',
    manage_program: null,
    login_ssid: null,
    access_key: 'CNB6HDKCNR',
    purchase_date: '2024-07-24',
    category: 'Printer',
    branch_name: 'BD8',
    remark: 'Printer ISD Site BangJak',
    status: 'active'
  },
  {
    ip_address: '192.168.8.22',
    device_name: 'AirCard ZTE MF65M Site BangJak BD8',
    brand_name: 'ZTE',
    model: 'MF65M',
    login_user: 'admin',
    login_password: 'ztepassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: '2024-07-24',
    category: 'Network & Security',
    branch_name: 'BD8',
    remark: 'Phone 095-6756354 Site BangJak',
    status: 'active'
  },

  // 4. BD15 (28 items)
  {
    ip_address: '192.168.99.7',
    device_name: 'Time Access Scan BD15',
    brand_name: 'ZKTeco',
    model: 'V3L',
    login_user: 'admin',
    login_password: 'adminpassword',
    manage_program: 'ZKBioAccess Web',
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD15',
    remark: 'WiFi .76',
    status: 'active'
  },
  {
    ip_address: '192.168.7.18',
    device_name: 'Time / Finger Access F1 BD15',
    brand_name: 'ZKTeco',
    model: 'F18',
    login_user: 'admin',
    login_password: 'adminpassword',
    manage_program: 'ZKTime 5.0 Program Manage',
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD15',
    remark: 'Time Access Scan BD15',
    status: 'active'
  },
  {
    ip_address: '192.168.7.9',
    device_name: 'PABX NEC SL1000 BD15',
    brand_name: 'NEC',
    model: 'SL1000',
    login_user: 'tech',
    login_password: '19911991',
    manage_program: 'WebManage 192.168.1.234',
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD15',
    remark: 'PABX Telephone System BD15 / ย้ายมาจาก Soi-10',
    status: 'active'
  },
  {
    ip_address: '203.151.54.109',
    device_name: 'Express Cloud',
    brand_name: 'Express',
    model: 'Express on Cloud',
    login_user: 'W10E073762-01',
    login_password: 'CST@acc01',
    manage_program: 'http://203.151.54.109',
    login_ssid: null,
    access_key: null,
    purchase_date: '2023-11-07',
    category: 'Server',
    branch_name: 'BD15',
    remark: 'ExpressI On Cloud of CST, S/N: W-10E-073762 (Lek)',
    status: 'active'
  },
  {
    ip_address: '192.168.1.9',
    device_name: 'NEC VoIP BD15 (Port 5060)',
    brand_name: 'NEC',
    model: 'SL1000',
    login_user: 'tech',
    login_password: '19911991',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD15',
    remark: 'SIP Port 5060',
    status: 'active'
  },
  {
    ip_address: '192.168.1.10',
    device_name: 'NEC VoIP BD15 (Port 10020)',
    brand_name: 'NEC',
    model: 'SL1000',
    login_user: 'tech',
    login_password: '19911991',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD15',
    remark: 'RTP Port 10020',
    status: 'active'
  },
  {
    ip_address: '192.168.1.15',
    device_name: 'CCTV DVR BD15',
    brand_name: 'T-Gard',
    model: 'PS-7908MI',
    login_user: 'admin',
    login_password: '12345',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'CCTV',
    branch_name: 'BD15',
    remark: 'CCTV Recorder BD15',
    status: 'active'
  },
  {
    ip_address: '192.168.1.241',
    device_name: 'Printer Epson L6190 BD15',
    brand_name: 'Epson',
    model: 'L6190',
    login_user: 'admin',
    login_password: 'epsonpassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Printer',
    branch_name: 'BD15',
    remark: 'Epson InkTank Printer BD15',
    status: 'active'
  },
  {
    ip_address: '192.168.1.242',
    device_name: 'Printer HP 130-134Fn BD15',
    brand_name: 'HP',
    model: 'LaserJet 130-134Fn',
    login_user: 'admin',
    login_password: 'hppassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Printer',
    branch_name: 'BD15',
    remark: 'HP LaserJet Printer BD15',
    status: 'active'
  },
  {
    ip_address: '192.168.1.244',
    device_name: 'Access Point F1 BD-15',
    brand_name: 'TP-Link',
    model: 'EAP620HD',
    login_user: 'admin',
    login_password: 'isit@dm%n',
    manage_program: null,
    login_ssid: 'CST-WiFi / CSTIntergroup',
    access_key: null,
    purchase_date: null,
    category: 'Access Point',
    branch_name: 'BD15',
    remark: 'PO2300222 (19/09/2566)',
    status: 'active'
  },
  {
    ip_address: '192.168.1.245',
    device_name: 'Access Point F2 BD-15',
    brand_name: 'TP-Link',
    model: 'EAP620HD',
    login_user: 'admin',
    login_password: 'isit@dm%n',
    manage_program: null,
    login_ssid: 'CST-WiFi / CSTIntergroup',
    access_key: null,
    purchase_date: null,
    category: 'Access Point',
    branch_name: 'BD15',
    remark: 'PO2300222 (19/09/2566)',
    status: 'active'
  },
  {
    ip_address: '192.168.1.246',
    device_name: 'Access Point F3 BD-15',
    brand_name: 'TP-Link',
    model: 'EAP620HD',
    login_user: 'admin',
    login_password: 'isit@dm%n',
    manage_program: null,
    login_ssid: 'CST-WiFi / CSTIntergroup',
    access_key: null,
    purchase_date: null,
    category: 'Access Point',
    branch_name: 'BD15',
    remark: 'PO2300222 (19/09/2566)',
    status: 'active'
  },
  {
    ip_address: '192.168.7.15',
    device_name: 'CCTV NVR ตึก 15',
    brand_name: 'HiKvision',
    model: 'DS-7616NI-K2',
    login_user: 'admin',
    login_password: '19911991',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'CCTV',
    branch_name: 'BD15',
    remark: 'Port 8100, HTTP 8181',
    status: 'active'
  },
  {
    ip_address: '49.0.69.34',
    device_name: 'AIS Fiber Router BD15',
    brand_name: 'AIS',
    model: 'ZTE H198A',
    login_user: 'admin',
    login_password: 'aispassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Network & Security',
    branch_name: 'BD15',
    remark: 'FixIP: 49.0.69.34, Account: 8804998142, Subnet 192.168.1.1',
    status: 'active'
  },
  {
    ip_address: '192.168.15.1',
    device_name: 'Rack 9U BD15',
    brand_name: 'Germany Export',
    model: '9U',
    login_user: null,
    login_password: null,
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Other',
    branch_name: 'BD15',
    remark: 'Rack 9U 15-BD-F2',
    status: 'active'
  },
  {
    ip_address: '192.168.15.2',
    device_name: 'FiberBox Receiver BD15',
    brand_name: 'Media Converter',
    model: 'MC200CM',
    login_user: null,
    login_password: null,
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Network & Security',
    branch_name: 'BD15',
    remark: 'FiberBox Receiver 15-BD-F2',
    status: 'active'
  },
  {
    ip_address: '192.168.15.3',
    device_name: 'Cisco Switch Hub #1 BD15',
    brand_name: 'Cisco',
    model: 'SG350-28',
    login_user: 'cisco_admin',
    login_password: 'ciscopassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Network & Security',
    branch_name: 'BD15',
    remark: 'Cisco Switch 1 (or Autoby SW) 15-BD-F2',
    status: 'active'
  },
  {
    ip_address: '192.168.15.4',
    device_name: 'Cisco Switch Hub #2 BD15',
    brand_name: 'Cisco',
    model: 'SG350-28',
    login_user: 'cisco_admin',
    login_password: 'ciscopassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Network & Security',
    branch_name: 'BD15',
    remark: 'Cisco Switch 2 (or Autoby SW) 15-BD-F2',
    status: 'active'
  },
  {
    ip_address: '192.168.15.5',
    device_name: 'UPS BD15',
    brand_name: 'APC',
    model: 'Smart-UPS 1500VA',
    login_user: null,
    login_password: null,
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Other',
    branch_name: 'BD15',
    remark: 'UPS Power Supply 15-BD-F2',
    status: 'active'
  },
  {
    ip_address: '192.168.15.6',
    device_name: 'NAS Storage QNAP TS-569L BD15',
    brand_name: 'QNAP',
    model: 'TS-569L',
    login_user: 'admin',
    login_password: 'qnapadminpass',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Server',
    branch_name: 'BD15',
    remark: 'NAS Storage 5-Bay 15-BD-F2',
    status: 'active'
  },
  {
    ip_address: '192.168.15.7',
    device_name: 'Printer Kyocera 3500i BD15',
    brand_name: 'Kyocera',
    model: '3500i',
    login_user: 'admin',
    login_password: 'kyocerapassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Printer',
    branch_name: 'BD15',
    remark: 'Kyocera Multi-function Printer 15-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.15.8',
    device_name: 'Printer Samsung SL-C-480FW BD15',
    brand_name: 'Samsung',
    model: 'SL-C-480FW',
    login_user: 'admin',
    login_password: 'samsungpass',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: '2024-03-01',
    category: 'Printer',
    branch_name: 'BD15',
    remark: 'Samsung Color Laser Printer Q-Air 15-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.15.9',
    device_name: 'Printer HP MFP-227-231fdw BD15',
    brand_name: 'HP',
    model: 'MFP-227-231fdw',
    login_user: 'admin',
    login_password: 'hppassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Printer',
    branch_name: 'BD15',
    remark: 'HP LaserJet Printer ACC 15-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.15.10',
    device_name: 'Access Point Cisco WAP300N #1 BD15',
    brand_name: 'Cisco',
    model: 'WAP300N',
    login_user: 'cisco_admin',
    login_password: 'ciscopassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Access Point',
    branch_name: 'BD15',
    remark: 'Access Point AIA 15-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.15.11',
    device_name: 'Access Point Cisco WAP300N #2 BD15',
    brand_name: 'Cisco',
    model: 'WAP300N',
    login_user: 'cisco_admin',
    login_password: 'ciscopassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Access Point',
    branch_name: 'BD15',
    remark: 'Access Point AIA 15-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.15.12',
    device_name: 'Access Point Cisco WAP300N #3 BD15',
    brand_name: 'Cisco',
    model: 'WAP300N',
    login_user: 'cisco_admin',
    login_password: 'ciscopassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'Access Point',
    branch_name: 'BD15',
    remark: 'Access Point AIA 15-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.15.13',
    device_name: 'Time / Door Access ZKT F18 F1 BD15',
    brand_name: 'ZKT',
    model: 'F18',
    login_user: 'admin',
    login_password: 'adminpassword',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'BD15',
    remark: 'Time / Door Access F1 AIA 15-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.15.14',
    device_name: 'DVR CCTV T-Grad PS-7908MI BD15',
    brand_name: 'T-Grad',
    model: 'PS-7908MI',
    login_user: 'admin',
    login_password: '12345',
    manage_program: null,
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'CCTV',
    branch_name: 'BD15',
    remark: 'DVR CCTV Recorder 15-BD',
    status: 'active'
  },
  {
    ip_address: '192.168.15.15',
    device_name: 'Printer Brother MFC-L2715DW BD15',
    brand_name: 'Brother',
    model: 'MFC-L2715DW',
    login_user: 'admin',
    login_password: 'brotherpass',
    manage_program: null,
    login_ssid: null,
    access_key: 'E78114L2N916057',
    purchase_date: '2024-03-01',
    category: 'Printer',
    branch_name: 'BD15',
    remark: 'Brother Multi-function Printer ACC POD2300639',
    status: 'active'
  },

  // 5. Other branches (2 items)
  {
    ip_address: '192.168.99.9',
    device_name: 'NEC VoIP System',
    brand_name: 'NEC',
    model: 'SL1000',
    login_user: 'tech',
    login_password: 'necpass123',
    manage_program: 'WebPro SL1000',
    login_ssid: null,
    access_key: null,
    purchase_date: null,
    category: 'VoIP & Time Access',
    branch_name: 'ซอย 10',
    remark: 'isacc เอ็นจิเนียริ่ง / ไอแซค มาเก็ตติ้ง',
    status: 'active'
  },
  {
    ip_address: '192.168.99.18',
    device_name: 'Printer Laser HQ',
    brand_name: 'HP',
    model: 'LaserJet Pro M130FN',
    login_user: 'admin',
    login_password: 'hppassword',
    manage_program: 'ASPD Corporation',
    login_ssid: null,
    access_key: null,
    purchase_date: '2019-04-10',
    category: 'Printer',
    branch_name: 'ระยอง',
    remark: 'ประจำแผนกบัญชี',
    status: 'active'
  }
];

async function runImport() {
  console.log('🚀 Step 1: Truncating network_devices table for clean multi-branch dataset...');
  await pool.query('DELETE FROM network_devices');
  await pool.query('ALTER TABLE network_devices AUTO_INCREMENT = 1');
  console.log('✅ Table cleaned.');

  console.log('\n🚀 Step 2: Inserting clean 66 multi-branch devices...');
  let insertedCount = 0;

  for (const item of devicesToImport) {
    await pool.query(`
      INSERT INTO network_devices (
        ip_address, device_name, brand_name, model, login_user, login_password,
        manage_program, login_ssid, access_key, purchase_date, category, branch_name, remark, status
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `, [
      item.ip_address,
      item.device_name,
      item.brand_name || null,
      item.model || null,
      item.login_user || null,
      item.login_password || null,
      item.manage_program || null,
      item.login_ssid || null,
      item.access_key || null,
      item.purchase_date || null,
      item.category,
      item.branch_name,
      item.remark || null,
      item.status || 'active'
    ]);
    insertedCount++;
  }

  console.log(`🎉 Done! Inserted ${insertedCount} devices.`);

  // Summary by branch
  const [branchRows] = await pool.query('SELECT branch_name, COUNT(*) as count FROM network_devices GROUP BY branch_name');
  console.log('\n📊 Device Breakdown by Branch in Database:');
  console.table(branchRows);

  process.exit(0);
}

runImport().catch(err => {
  console.error('❌ Import error:', err);
  process.exit(1);
});
